### ISSUE TITLE
[MC 1.18] [Forge 38.0.15] MixinTransformer Error on clean install

### ISSUE THREAD

**Issue by MoltenLichQueen** [TelepathicGrunt/NoNullProcessors#2]
On a fresh install of Forge 1.18, No Null Processes loads to the main menu fine but throws a Critical Error -1 on clicking the Singleplayer button. Multiplayer button is unaffected, as are the mods button, Realms button, Options, Language and Accessibility Buttons. 

Minecraft 1.18, Forge 38.0.15. Forge logs and crash reports attached, 

[crash-2021-12-09_08.47.36-client.txt](https://github.com/TelepathicGrunt/NoNullProcessors/files/7686952/crash-2021-12-09_08.47.36-client.txt)
[latest.log](https://github.com/TelepathicGrunt/NoNullProcessors/files/7686954/latest.log)

**Comment by MoltenLichQueen** [comment]
Apologies if I left anything out or did something wrong, I'm not familiar with Github at all.

**Comment by TelepathicGrunt** [comment]
My mixins are broken so I need to figure out how to fix them to work outside my development environment.

**Comment by TelepathicGrunt** [comment]
fixed in v2.0.1
